[item]
id = FLOW-mov6is6h-h9gz72
title = Description Markdown
description = ## Summary
    
    Support lists and headings in the description field with Markdown.
    
    ## Allow
    
    For now, we only allow:
    
    - Headings
    - Lists
    - Paragraphs
    - **Bold**
    - **Italic**
    
    ## Not currently allowed
    
    [Links](https://example.com)
owner = millrace@example.com
swimlane = Default
column = Doing
sort_order = 10
created = 2026-05-07T07:43:11.670Z
