[item]
id = FLOW-mov6is6h-h9gz72
title = Description Markdown
description = ## Summary
    
    Support lists and headings in the description field with Markdown.
    
    ## Allow
    
    For now, we only allow a simple set of markdown options:
    
    - Headings
    - Lists
    - Nested lists
    - Paragraphs
    - **Bold**
    - *Italic*
    - [Links](https://example.com)
owner = millrace@example.com
swimlane = Default
column = Done
sort_order = 290
created = 2026-05-07T07:43:11.670Z
closed = 2026-05-07T08:42:25.976Z
